//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReflectiveCode.GMinder.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Window : global::System.Configuration.ApplicationSettingsBase {
        
        private static Window defaultInstance = ((Window)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Window())));
        
        public static Window Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250, 200")]
        public global::System.Drawing.Size PreviewSize {
            get {
                return ((global::System.Drawing.Size)(this["PreviewSize"]));
            }
            set {
                this["PreviewSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Size ReminderSize {
            get {
                return ((global::System.Drawing.Size)(this["ReminderSize"]));
            }
            set {
                this["ReminderSize"] = value;
            }
        }
    }
}
